create table if not exists public.raw_gov_tax_data (
  id bigint generated by default as identity primary key,
  source_api text not null,
  fetched_at timestamptz default now() not null,
  payload_json jsonb not null
);

comment on table public.raw_gov_tax_data is 'Stores raw JSON responses from Government Tax APIs (Bronze Layer)';
