// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jksbkhbgggytymhgnerh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imprc2JraGJnZ2d5dHltaGduZXJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1OTkzMTAsImV4cCI6MjA3MzE3NTMxMH0.PCk8gUCUbFQsB91MYjbdzImQb9UvhlP2w7p9Gh7Bfb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});